apiVersion: v1
kind: Service
metadata:
  name: demo-ip
  labels:
    app: {{ template "name" . }}-ip
spec:
  selector:
    app: {{ template "name" . }}
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "35.201.122.208"