apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: {{ template "name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{ if and (not .Values.varnish.enabled) (.Values.externaldns.enabled) -}}
  annotations:
    {{- range $key, $value := .Values.externaldns.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end -}}
  {{- end }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ template "name" . }}-nginx
    release: {{ .Release.Name }}
