apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-postgresql
  labels:
    app: {{ template "name" . }}-postgresql
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.php.replicaCount }}
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - image: postgres:9-alpine
          name: postgresql
          env:
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_USER
              value: symfony
# Do not hardcode this value in prod! Use a k8s's secret instead!!
            - name: POSTGRES_PASSWORD
              value: symfony
          ports:
            - containerPort: 5432
              name: postgresql
      #    volumeMounts:
      #      - name: postgresql-persistent-storage
      #        mountPath: /var/lib/postgresql/data
      #volumes:
      #  - name: postgresql-persistent-storage
      #    gcePersistentDisk:
      #      pdName: postgresql-disk
      #      fsType: ext4
