language: php

dist: trusty

sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

# If you want to use multi branch deployment or branch naming, set MULTI_BRANCH value to 1 and set your DEPLOYMENT_BRANCH.
# Don't forget to change the repo name to fit your needs.
# Check that all needed travis environment variables are set.
before_install:
  - ./ci/before_install.sh
  - source ./ci/.env

before_script:
  - phpenv config-rm xdebug.ini
  - sudo service mysql stop
  - sudo service postgresql stop
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- --version v2.9.1;
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - ./ci/test.sh

# Get kubectl and make it executable
# Create the travis service account access file from travis environment variables
# Connect to the project as travis service account by gcloud using the travis service account access file we just created above and configure project.
# Create the needed bucket in which to push builds.
before_deploy:
  - ./ci/before_deploy.sh
  - |
    if [[ "${MULTI_BRANCH}" == "0" && "${CURRENT_CI}" == "travis" && -n ${CI_TAG} ]]; then
      gsutil mb -p ${PROJECT_ID} -l eu gs://${ADMIN_BUCKET} || echo "Admin bucket exists";
      gsutil mb -p ${PROJECT_ID} -l eu gs://${CLIENT_BUCKET} || echo "Client bucket exists";
    elif [[ "${CURRENT_CI}" == "travis" && ${TRAVIS_PULL_REQUEST} == 'true' ]]
    then
      gsutil mb -p ${PROJECT_ID} -l eu gs://${ADMIN_BUCKET} || echo "Admin bucket exists"
      gsutil mb -p ${PROJECT_ID} -l eu gs://${CLIENT_BUCKET} || echo "Client bucket exists"
    fi;

# Deploy images and buckets according to the current context, create or update Kubenetes release with updated informations.
deploy:
  - provider: script
    script: bash ci/deploy.sh
    skip_cleanup: true
    on:
      branch: ${DEPLOYMENT_BRANCH}
      repo: ${REPOSITORY}
      condition: ${CURRENT_CI} == 'travis' && $MULTI_BRANCH == 0 && ${TRAVIS_PULL_REQUEST} == 'false' && -n ${CI_TAG}
  - provider: script
    script: bash ci/deploy.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
      condition: ${CURRENT_CI} == 'travis' && ${MULTI_BRANCH} == 1 && ${TRAVIS_PULL_REQUEST} == 'true'
  - provider: script
    script: bash ci/buckets_builds.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
      condition: ${CURRENT_CI} == 'travis'  && ${MULTI_BRANCH} == 0 && ${TRAVIS_PULL_REQUEST} == 'false' && -n ${CI_TAG}
  - provider: script
    script: bash ci/buckets_builds.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
        condition: ${CURRENT_CI} == 'travis' && ${MULTI_BRANCH} == 1 && ${TRAVIS_PULL_REQUEST} == 'true'
  - provider: script
    script: bash ci/buckets_deploy.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
      condition: ${CURRENT_CI} == 'travis' && ${MULTI_BRANCH} == 0 && ${TRAVIS_PULL_REQUEST} == 'false' && -n ${CI_TAG}
  - provider: script
    script: bash ci/buckets_deploy.sh
    skip_cleanup: true
    on:
      repo: ${REPOSITORY}
      condition: ${CURRENT_CI} == 'travis' && ${MULTI_BRANCH} == 1 && ${TRAVIS_PULL_REQUEST} == 'true'

