sudo: required

services:
  - docker

cache:
  yarn: true
  directories:
    - admin/node_modules
    - client/node_modules

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.6.1-linux-amd64.tar.gz
  - tar xzf helm-v2.6.1-linux-amd64.tar.gz
  - npm install -g react-scripts
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose up -d
  - linux-amd64/helm lint api/helm/api/
  - sleep 20
  - sh -c "cd admin && PUBLIC_URL="/api-demo-admin-test" yarn install && yarn build"
  - sh -c "cd client && PUBLIC_URL="/api-demo-client-test" yarn install && yarn build"
  - docker-compose exec php composer install -o -n
  - docker-compose exec php bin/console security:check
  - docker-compose exec php bin/console doctrine:schema:validate --skip-sync
  - docker-compose exec php bin/console doctrine:schema:drop --force
  - docker-compose exec php bin/console doctrine:schema:create
  - docker-compose exec php bin/console hautelook:fixtures:load -n
  - docker-compose exec php bin/console doctrine:schema:drop --env=test --force
  - docker-compose exec php bin/console cache:warmup --env=test
  - docker-compose exec php bin/behat
  - curl http://localhost
  - curl http://localhost:81
  - curl http://localhost:8080
  - curl http://localhost:8081
  - curl -k https://localhost
  - curl -k https://localhost:444
  - curl -k https://localhost:8443
  - curl -k https://localhost:8444

deploy:
  - provider: gcs
    skip_cleanup: true
    access_key_id:
      secure: "e5Cqd92qs6Fh0z3ry2D0S9kwDQixXJrd/RnItu0DVT7chAzibDvDFXiThB6RMXcPa2CugpoAGoSmXOiIzukJGCBHVcz8TUrqaQo8ASovvbV2wXQAqtQ6nOHFgJrsPi86cfUDAXtOoV7NCm74xR7x0onYV2JUlPUUOsuB7L5vHEocd2HyPZOAcl2y6DAZYTwtcoIR+DP0/9IbHItyg9igwSoNNtQMWWIK1TBQ7kWBzIbCO2Ob92wO9Rs6mzQKE+axKzkNUmVEVgCEwEXmdpeDChP4WlesFeTjjntmwSMhi2HvxCNN/LC5CmypH1n99xTGHzbTRe6ZYFfs16UVTR0Hxb++qy0vbJuQs5i4MEH+5kaqmlYS4iVRBPP0qJy1ZWZfCx4lNnE0IQ8lJROpOT0ocfP0uNbCAGdBuH/vBTc7xv8/aOR66qYvpCnaCuCNjqUrmWj3wM/yaKwC8lcA/lq27v4c/rWtDzNh/JbL6PWOlsLskFEslVWrmai6gyTWtNL66yLASVrTwp2HvZ5mvtrueB3u5i6k5ZaFwsPzSEPXrHFW1XH9Ipfm2jjBf7AK7Y2U+e8851PCuKPU4au0WY04CtRlui4Z944FJBj/Ciw6/oYZWE/sWYHKmeNn8ySdY3ALSbjJx1Cuy60SkoLdxfesbgv1TcalNI1wEvWR1CHxT2M="
    secret_access_key:
      secure: "ZBQp4j+O89OmxeSSOruYeaSTIjWCVGQO/woeft8uK4iEaNFm1QUJUOw7imZL+rur2BIR9vJybSgNMz04K+/wZFfM2/JLEUCvrhXq5ffijV1ZS1sQst+4cDJpkfvzdKCgXoH2w9nbyn0K6fIL0XMA2eaL+ZV5AQBOqnwhR6MUEZt7aOfbEhL759nanmE9PGozM8ma1f97jVhwf9VQCjOf/LsERjwQc8UL3WLr1MkoVuMOqhtQihAU/fGS6OOoc0Z+dqQFhxuVDmGCz1VKc6rikZYfNutWQLKn5w0BA5tFdMeNW2W2MOw5BkEY+0UzVVMKQ01lBeiEmtd4JU/a1buCtNs4xpXal7Ewea82Nu244BSqNpAnIe28KfN+SmAtJHCJy/LoT4Iae3hvpRQE0jJvzAf2B1rIcmI2NQqFgleBnPw5WphiWVdoy+beKlF1W1bCKr9SHWvBd7chOMcFZVkpZkZuA0KI9Y2bUZGWGz1QM18RIgkfzTK4UM8hNipc3IsFV9cWHBXARb8WcO751zNJkENU413N9Not7Lhbdl5ruUf3Qz9yT+2gQd9SD97ErccAMqvRcoqAHWF7yDvQjcQKnNNfhXqP+gJ0xtFdRtG+TMHtib2NKao6NsAsWQKoLT0Vc3RmMm/RYWXmc9bVz1rt07Ae7xfi9GddG2HEbZlGjlk="
    bucket: api-demo-admin-test
    acl: public-read
    local-dir: admin/build
    on:
      branch: master
  - provider: gcs
    skip_cleanup: true
    access_key_id:
      secure: "e5Cqd92qs6Fh0z3ry2D0S9kwDQixXJrd/RnItu0DVT7chAzibDvDFXiThB6RMXcPa2CugpoAGoSmXOiIzukJGCBHVcz8TUrqaQo8ASovvbV2wXQAqtQ6nOHFgJrsPi86cfUDAXtOoV7NCm74xR7x0onYV2JUlPUUOsuB7L5vHEocd2HyPZOAcl2y6DAZYTwtcoIR+DP0/9IbHItyg9igwSoNNtQMWWIK1TBQ7kWBzIbCO2Ob92wO9Rs6mzQKE+axKzkNUmVEVgCEwEXmdpeDChP4WlesFeTjjntmwSMhi2HvxCNN/LC5CmypH1n99xTGHzbTRe6ZYFfs16UVTR0Hxb++qy0vbJuQs5i4MEH+5kaqmlYS4iVRBPP0qJy1ZWZfCx4lNnE0IQ8lJROpOT0ocfP0uNbCAGdBuH/vBTc7xv8/aOR66qYvpCnaCuCNjqUrmWj3wM/yaKwC8lcA/lq27v4c/rWtDzNh/JbL6PWOlsLskFEslVWrmai6gyTWtNL66yLASVrTwp2HvZ5mvtrueB3u5i6k5ZaFwsPzSEPXrHFW1XH9Ipfm2jjBf7AK7Y2U+e8851PCuKPU4au0WY04CtRlui4Z944FJBj/Ciw6/oYZWE/sWYHKmeNn8ySdY3ALSbjJx1Cuy60SkoLdxfesbgv1TcalNI1wEvWR1CHxT2M="
    secret_access_key:
      secure: "ZBQp4j+O89OmxeSSOruYeaSTIjWCVGQO/woeft8uK4iEaNFm1QUJUOw7imZL+rur2BIR9vJybSgNMz04K+/wZFfM2/JLEUCvrhXq5ffijV1ZS1sQst+4cDJpkfvzdKCgXoH2w9nbyn0K6fIL0XMA2eaL+ZV5AQBOqnwhR6MUEZt7aOfbEhL759nanmE9PGozM8ma1f97jVhwf9VQCjOf/LsERjwQc8UL3WLr1MkoVuMOqhtQihAU/fGS6OOoc0Z+dqQFhxuVDmGCz1VKc6rikZYfNutWQLKn5w0BA5tFdMeNW2W2MOw5BkEY+0UzVVMKQ01lBeiEmtd4JU/a1buCtNs4xpXal7Ewea82Nu244BSqNpAnIe28KfN+SmAtJHCJy/LoT4Iae3hvpRQE0jJvzAf2B1rIcmI2NQqFgleBnPw5WphiWVdoy+beKlF1W1bCKr9SHWvBd7chOMcFZVkpZkZuA0KI9Y2bUZGWGz1QM18RIgkfzTK4UM8hNipc3IsFV9cWHBXARb8WcO751zNJkENU413N9Not7Lhbdl5ruUf3Qz9yT+2gQd9SD97ErccAMqvRcoqAHWF7yDvQjcQKnNNfhXqP+gJ0xtFdRtG+TMHtib2NKao6NsAsWQKoLT0Vc3RmMm/RYWXmc9bVz1rt07Ae7xfi9GddG2HEbZlGjlk="
    bucket: api-demo-client-test
    acl: public-read
    local-dir: client/build
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: api/bin/deploy.sh
    on:
      branch: master