sudo: required

services:
    - docker

script:
    - docker-compose build
    - docker-compose run web composer install -o -n
    - docker-compose run web bin/console security:check
    - docker-compose run web bin/console doctrine:schema:validate --skip-sync
    - docker-compose up -d
    - docker-compose run web bin/console doctrine:schema:create
    - docker-compose run web bin/console hautelook:fixtures:load -n
    - docker-compose run web bin/console doctrine:schema:drop --env=test --force
    - docker-compose run web bin/console cache:warmup --env=test
    - docker-compose run web bin/behat
