# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    review.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { itemReviewed: 'exact' } ]
        tags: [ { name: 'api_platform.filter' } ]
