version: 2.1

commands:
  formatbranch:
    description: "Well format branch name"
    steps:
      - run: |
          echo 'CHANGE BRANCH ENV VAR'
          echo 'export BRANCH=`echo $CIRCLE_BRANCH | sed -E "s/\//-/g"` >> $BASH_ENV
          echo 'export BRANCH=${BRANCH,,} >> $BASH_ENV
          source $BASH_ENV

executors:
  demo-executor:
    machine: true
    environment:
      MULTI_BRANCH: 0
      REPOSITORY: api-platform/demo
      DEPLOYMENT_BRANCH: master
      PROD_DNS: demo.api-platform.com

# Dont forget to add the needed environment variables in you circleCI repository.
jobs:
  prepare:
    executor: demo-executor
    steps:
      - formatbranch
      - run: |
          printenv
          if [[ -z "${PROJECT_ID}" ]]; then echo 'PROJECT_ID is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${ADMIN_BUCKET}" ]]; then echo 'ADMIN_BUCKET is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${CLIENT_BUCKET}" ]]; then echo 'CLIENT_BUCKET is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${CI_SERVICE_ACCOUNT}" ]]; then echo 'TRAVIS_SERVICE_ACCOUNT is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${DATABASE_USER}" ]]; then echo 'DATABASE_USER is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${DATABASE_PASSWORD}" ]]; then echo 'DATABASE_PASSWORD is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${DATABASE_NAME}" ]]; then echo 'DATABASE_NAME is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${DEV_ADMIN_BUCKET}" && MULTI_BRANCH == "1" ]]; then echo 'DEV_ADMIN_BUCKET is not defined in your travis environement variables.'; exit 1; fi
          if [[ -z "${DEV_CLIENT_BUCKET}" && MULTI_BRANCH == "1" ]]; then echo 'DEV_CLIENT_BUCKET is not defined in your travis environement variables.'; exit 1; fi
          ./ci/env.sh

  deploy:
    executor: demo-executor
    steps:
      - formatbranch

workflows:
  version: 2
  # Workflow name
  workflow:
    jobs:
    - prepare
    - deploy:
        requires:
          - prepare
#        filters:
#          branch:
#            only:
#              master



# Workflow example

#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#    - build
#    - deploy-stage:
#        requires:
#        - build
#        filters:
#          branches:
#            only: staging
#    - deploy-prod:
#        requires:
#        - build
#        filters:
#          branches:
#            only: master


# Deploy example

#jobs:
#  deploy:
#    executor: s3/default
#    steps:
#    - s3/deploy:
#        from: "somepath/somefile"
#        to: $S3BUCKETURI
#        overwrite: false