version: 2.1

commands:
  formatbranch:
    description: "Well format branch name"
    steps:
      - run: |
          echo 'CHANGE BRANCH ENV VAR'
          echo 'export BRANCH=`echo $CIRCLE_BRANCH | sed -E "s/\//-/g"` >> $BASH_ENV
          echo 'export BRANCH=${BRANCH,,} >> $BASH_ENV
          source $BASH_ENV

executors:
  demo-executor:
    docker:
      - image: circleci/php:7.2.10-fpm-stretch-node-browsers-legacy

# Dont forget to add the needed environment variables in you circleCI repository.
jobs:
  prepare:
    executor: demo-executor
    steps:
      - checkout
      - formatbranch
      - run: |
          ./ci/before_deploy.sh
          source ./ci/env.sh
          source $BASH_ENV

  deploy:
    executor: demo-executor
    steps:
      - formatbranch
      - run : |
          phpenv config-rm xdebug.ini
          sudo service mysql stop
          sudo service postgresql stop
          curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash -s -- --version v2.9.1;
          npm install -g react-scripts
          while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
          ./ci/test.sh

workflows:
  version: 2
  # Workflow name
  workflow:
    jobs:
    - prepare
    - deploy:
        requires:
          - prepare
#        filters:
#          branch:
#            only:
#              master



# Workflow example

#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#    - build
#    - deploy-stage:
#        requires:
#        - build
#        filters:
#          branches:
#            only: staging
#    - deploy-prod:
#        requires:
#        - build
#        filters:
#          branches:
#            only: master


# Deploy example

#jobs:
#  deploy:
#    executor: s3/default
#    steps:
#    - s3/deploy:
#        from: "somepath/somefile"
#        to: $S3BUCKETURI
#        overwrite: false