version: 2.1

commands:
  formatbranch:
    description: "Well format branch name"
    steps:
      - run: |
          echo 'CHANGE BRANCH ENV VAR'
          echo 'export BRANCH=`echo $CIRCLE_BRANCH | sed -E "s/\//-/g"` >> $BASH_ENV
          echo 'export BRANCH=${BRANCH,,} >> $BASH_ENV
          source $BASH_ENV

executors:
  demo-executor:
    machine: true
    environment:
      MULTI_BRANCH: 0
      REPOSITORY: api-platform/demo
      DEPLOYMENT_BRANCH: master
      PROD_DNS: demo.api-platform.com

jobs:
  test:
    executor: demo-executor
    steps:
      - run:
          command: formatbranch
      - run:
          command: printenv

  deploy:
    executor: demo-executor
    steps:
      - run:
          command: |
            formatbranch
            printenv

workflows:
  version: 2
  # Workflow name
  workflow:
    jobs:
    - test
    - deploy:
        requires:
          - test
#        filters:
#          branch:
#            only:
#              master



# Workflow example

#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#    - build
#    - deploy-stage:
#        requires:
#        - build
#        filters:
#          branches:
#            only: staging
#    - deploy-prod:
#        requires:
#        - build
#        filters:
#          branches:
#            only: master


# Deploy example

#jobs:
#  deploy:
#    executor: s3/default
#    steps:
#    - s3/deploy:
#        from: "somepath/somefile"
#        to: $S3BUCKETURI
#        overwrite: false