name: CD

on:
  push:
    branches:
      - main
  pull_request: ~

env:
  GKE_CLUSTER: api-platform-demo
  GCE_ZONE: europe-west1-c

jobs:
  build:
    name: Build
    if: github.repository == 'api-platform/demo'
    uses: ./.github/workflows/build.yml
    with:
      tags: |
        type=ref,event=pr,prefix=pr-,priority=1000
        type=ref,event=branch,priority=900
      push: true
      gke-cluster: $GKE_CLUSTER
      gke-zone: $GCE_ZONE
    secrets:
      gke-credentials: ${{ secrets.GKE_SA_KEY }}
      gke-project: ${{ secrets.GKE_PROJECT }}

  deploy:
    name: Deploy
    needs: [ build ]
    if: github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      url: demo.api-platform.com
      docker-images-version: main
      cors: ^https?://demo\\.api-platform\\.com$
      release: main
      namespace: main
      gke-cluster: $GKE_CLUSTER
      gke-zone: $GCE_ZONE
    secrets:
      gke-credentials: ${{ secrets.GKE_SA_KEY }}
      gke-project: ${{ secrets.GKE_PROJECT }}
      cloudflare-api-token: ${{ secrets.CF_API_TOKEN }}
      cloudflare-zone-id: ${{ secrets.CF_ZONE_ID }}

  feature-deploy:
    name: Deploy
    needs: [ build ]
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ needs.build.outputs.version }}
      url: ${{ needs.build.outputs.version }}-demo.api-platform.com
      docker-images-version: latest
      cors: ^https?://${{ needs.build.outputs.version }}-demo\\.api-platform\\.com$
      release: ${{ needs.build.outputs.version }}
      namespace: ${{ needs.build.outputs.version }}
      gke-cluster: $GKE_CLUSTER
      gke-zone: $GCE_ZONE
    secrets:
      gke-credentials: ${{ secrets.GKE_SA_KEY }}
      gke-project: ${{ secrets.GKE_PROJECT }}
      cloudflare-api-token: ${{ secrets.CF_API_TOKEN }}
      cloudflare-zone-id: ${{ secrets.CF_ZONE_ID }}
