name: Deploy

on:
  workflow_call:
    inputs:
      url:
        type: string
        description: URL

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/script.js
          flags: --out json=results.json
        env:
          TARGET: ${{ inputs.url }}
