# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
name: Upgrade

on:
  push:
    branches:
      - chore/release-workflow
  workflow_dispatch: ~

jobs:
  upgrade:
    name: Upgrade
    if: ${{ github.repository == 'api-platform/demo' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          tools: composer
      -
        name: Get Composer Cache Directory
        id: composer-cache
        working-directory: api
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      -
        name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      -
        name: Install Dependencies
        working-directory: api
        run: composer install --prefer-dist
      -
        name: Update API Platform Dependencies
        working-directory: api
        run: composer update "api-platform/*"
      -
        name: Show git diff
        working-directory: api
        run: git diff
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/api-platform
          commit-message: "chore: upgrade API Platform"
          title: Upgrade API Platform
          assignees: vincentchalamon
          add-paths: |
            api/composer.*
